### ISSUE TITLE
What is the migration path from 0.0.5 to 0.0.7

### ISSUE THREAD

**Issue by johansmitsnl** [yaleman/axum-csp#1]
I upgraded from `0.0.5` to `0.0.7` and [CspSetBuilder](https://docs.rs/axum-csp/0.0.5/axum_csp/struct.CspSetBuilder.html) has been removed. How should this be done in the new version?

Also `CspValue` needs a `&'static str`. This is difficult to use when iterating. Why did you change it from `String` to `&'static str`?

The main branch did not contain the `0.0.7` of `axum-csp` but it is in a support branch, why is this not on the main branch?

edit: Added `CspValue` question

**Comment by yaleman** [comment]
(I moved the package and this issue to a new repo, to make things easier in future)

**Comment by yaleman** [comment]
That makes sense, I'm not even sure why I changed it to be honest... clearly I was doing something weird, sorry 😄. I've reverted it back to String. 

Can you have a look through the current version in this repo and see if it all works for you and make sense? I'll admit I'm definitely more a hacks-at-things-until-they-work kinda guy more than a real developer 😇

**Comment by yaleman** [comment]
@johansmitsnl any issues at this point?

**Comment by johansmitsnl** [comment]
@yaleman unable to work on the project since I reported it. Sorry for the delay of feedback. Hopefully this or next weekend I find the time to work on it. Will definitely let you know the feedback.

**Comment by yaleman** [comment]
No worries, thought I'd check 😄

**Comment by yaleman** [comment]
I take it this can be closed @johansmitsnl ? 😄

**Comment by johansmitsnl** [comment]
@yaleman the project is active again and I want to review this part tonight.

**Comment by johansmitsnl** [comment]
With the main branch I don't have the issue anymore.
