### ISSUE TITLE
wasm-unsafe-eval is missing

### ISSUE THREAD

**Issue by johansmitsnl** [yaleman/axum-csp#25]
[wasm-unsafe-eval](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_webassembly_execution)

Implementing a wasm enabled site I also need this attribute.

Thanks!

**Comment by yaleman** [comment]
Could you please PR the change in? I'm not going to have much time over the next week or two to get that done - just needs the new values similar to #22

**Comment by johansmitsnl** [comment]
Added more items and sorted the enum list #26

**Comment by yaleman** [comment]
Publishing 0.0.9 based on this, thanks!
